### ISSUE TITLE
The question of calling "get_point_wise_lab" in gen_pts.py

### ISSUE THREAD

**Issue by boxiangzhang0810** [DC1991/FS_Net#2]
Hello, I have read your introduction and prepared the CAMERA dataset. After I used the code in 'object-deformnet', I found it is difficult to call "get_point_wise_lab" in "gen_pts.py". Especially, the parameters "ps" and "renderer" puzzle me. I seeked the two parameters everywhere in this project and found nothing about them. So I wonder how to call the function "get_point_wise_lab". Thanks for your help!

**Comment by DC1991** [comment]
Hi @boxiangzhang0810 ,

Sorry for that, I forget to upload the renderer function. I will upload the missing code by tomorrow. Thanks for your patience.

**Comment by boxiangzhang0810** [comment]
Thanks for your uploading code! When I run the code, I think the parameters in "get_point_wise_lab" correspond to the dataset's base path, the fold about each scene, the renderer, and the save path. The renderer only supports the '.ply' format. I want to know how to transform the '.obj' format of CAMERA and Real into '.ply' format. Thanks for your help!

**Comment by boxiangzhang0810** [comment]
Thanks for your new uploading code! I have prepared the data. When I wanna run "Train.py", I find the "data_loader_fsnet" and "load_pts_train_cate" don't exist in current work. So I want to know more details about them. Thanks for your help!

**Comment by DC1991** [comment]
@boxiangzhang0810 Thanks for your interesting in the work, I will upload the training details in next few weeks, thanks for your patience.

**Comment by DC1991** [comment]
Training code uploaded.
