### ISSUE TITLE
Question about pretrained weights and evaluation code (NOCS-REAL, LINEMOD).

### ISSUE THREAD

**Issue by trevor-taeyeop** [DC1991/FS_Net#4]
Thanks for sharing your work. 
Do you have a plan to release the pretrained weights and evaluation code on the NOCS and Linemod dataset??  (Include Ablation study)
It will really help me to understand your methods.

**Comment by DC1991** [comment]
Hi, thanks for your interest in our work. I will upload more details about our work soon, thanks for your patience.

**Comment by trevor-taeyeop** [comment]
Does your method has each model for each category??? (ex, 6 models for 6 categories)

**Comment by DC1991** [comment]
Yes, but for the 2D detection part, we use one YOLO model for all categories.

**Comment by dschaehi** [comment]
> Hi, thanks for your interest in our work. I will upload more details about our work soon, thanks for your patience.

Thanks for the interesting work! I would also appreciate if you could make it easier to reproduce the results in the paper. A guide for training the model from scratch to testing and generating all the results will be really nice. At the moment this is unfortunately not possible without digging into the code and making sense of it.

**Comment by DC1991** [comment]
> > Hi, thanks for your interest in our work. I will upload more details about our work soon, thanks for your patience.
> 
> Thanks for the interesting work! I would also appreciate if you could make it easier to reproduce the results in the paper. A guide for training the model from scratch to testing and generating all the results will be really nice. At the moment this is unfortunately not possible without digging into the code and making sense of it.

You can find how to train in the readme. For other relevant materials, since I am busy with my graduation, I will upload them after this busy period.
