### ISSUE TITLE
yolov3 pre training model

### ISSUE THREAD

**Issue by FlashDoghuhu** [DC1991/FS_Net#5]
Thank the author for his contribution. Will you release your yolov3 pre training model for the test set and the test scenarios of all real data sets? Instead of just one scene.

**Comment by DC1991** [comment]
Hi @FlashDoghuh, I will upload all the trained models in near future. Thanks for your interest in the work.

**Comment by Liuchongpei** [comment]
Same question (*￣︶￣)

**Comment by FlashDoghuhu** [comment]
> Same question (*￣︶￣)

Hello, as a Chinese from Wuhan, would you like to leave a personal contact information for exchange? QQ or wechat
